# Comando para executar: docker compose up --build --force-recreate
version: '3.8'

networks:
  tech-challenge-network:
    driver: bridge

volumes:
  pgdata:

services:

  #  ##############################################
  #  tech-challenge-service:
  #    container_name: tech-challenge
  #    image: tech-challenge
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    ports:
  #      - '8080:8080'
  #      - '5006:5006'
  #    environment:
  #      DB_HOST: db_tech_challenge
  #      DB_PORT: 5432
  #      ADDITIONAL_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5006 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
  #    depends_on:
  #      - db_tech_challenge

  db_postgres:
    container_name: db_postgres
    image: 'postgres:13.4'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tech-challenge
    ports:
      - "5432:5432"
      - '5005:5005'
    volumes:
      - pgdata:/var/lib/postgresql/data