server:
  port: ${PORT:8080}
  error:
    include-message: always

spring:
  application:
    name: tech-challenge-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/tech-challenge
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization:
  output:
    ansi:
      enabled: Always
  sql:
    init:
      mode: always  #colocado para subir data.sql

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

mercado-pago:
  url: "https://api.mercadopago.com"
  access-token: "Bearer APP_USR-151362775144770-012219-ad26be97b5a2ceab5965aaf6409a0d70-1650421194"
  notification-url: ${NOTIFICATION_URL:https://warm-sheepdog-secondly.ngrok-free.app/order/notifications}