server:
  port: 8080
  error:
    include-message: always


spring:
  application:
    name: tech-challenge-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/tech-challenge?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      #     ddl-auto: create #toda a vez que subir vai limpar o banco so para teste
      dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
    output:
      ansi:
        enabled: Always
    defer-datasource-initialization: true  #colocado para subir data.sql
  sql:
    init:
      mode: always  #colocado para subir data.sql

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

mercadopago:
  url: "https://api.mercadopago.com"
  userid: 115491705
  idcaixa: "FIAPFOOD02CAIXA"
  accesstoken: "Bearer TEST-7092785707123439-053021-f828a5ccadd4d79ecad74ced9b45c70c-115491705"
