server:
  port: 8088
  error:
    include-message: always


spring:
  application:
    name: tech-challenge-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/tech-challenge
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      #      ddl-auto: create #toda a vez que subir vai limpar o banco so para teste
      dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
    output:
      ansi:
        enabled: Always
    defer-datasource-initialization: true  #colocado para subir data.sql
  sql:
    init:
      mode: always  #colocado para subir data.sql

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

mercadopago:
  url: "https://api.mercadopago.com"
