apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge
  labels:
    app: tech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge
  template:
    metadata:
      labels:
        app: tech-challenge
    spec:
      initContainers:
        - name: wait-for-lb
          image: bitnami/kubectl:latest
          command: [ "/bin/sh", "-c" ]
          env:
            - name: ENVIRONMENT_DEPLOY
              value: "AWS" # Configuração para ambiente AWS
          args:
            - |
              echo "Valor da variável ENVIRONMENT_DEPLOY: $ENVIRONMENT_DEPLOY"
              if [ "$ENVIRONMENT_DEPLOY" != "AWS" ]; then
                echo "Ambiente não é AWS. Ignorando a atualização do Load Balancer."
                exit 0
              fi

              SERVICE_NAME="tech-challenge-service"
              NAMESPACE="default"
              echo "Aguardando Load Balancer IP..."
              while true; do
                EXTERNAL_IP=$(kubectl get svc $SERVICE_NAME -n $NAMESPACE -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
                if [ -n "$EXTERNAL_IP" ]; then
                  break
                fi
                echo -n "."
                sleep 10
              done
              echo "Load Balancer IP obtido: $EXTERNAL_IP"

              # Atualiza o ConfigMap com a nova URL
              kubectl create configmap tech-challenge-config --from-literal=notification-url=http://$EXTERNAL_IP/order/notifications --dry-run=client -o yaml | kubectl apply -f -
      containers:
        - name: tech-challenge
          image: josevitordurante/tech-challenge:latest
          ports:
            - containerPort: 8088
          env:
            - name: PORT
              value: "8088"
            - name: DB_HOST
              value: postgresql-service
            - name: DB_PORT
              value: "5432"
            - name: NOTIFICATION_URL
              valueFrom:
                configMapKeyRef:
                  name: tech-challenge-config
                  key: notification-url
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
