apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8088
      nodePort: 30007
  selector:
    app: tech-challenge
