apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge
  labels:
    app: tech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge
  template:
    metadata:
      labels:
        app: tech-challenge
    spec:
      containers:
        - name: tech-challenge
          image: josevitordurante/tech-challenge:latest
          ports:
            - containerPort: 8088
          env:
            - name: PORT
              value: "8088"
            - name: DB_HOST
              value: postgresql-service
            - name: DB_PORT
              value: "5432"
            - name: NOTIFICATION_URL
              value: tech-challenge-service/order/notifications
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
