apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-and-configmap-access
  namespace: default
rules:
  - apiGroups: [ "" ]
    resources: [ "services", "configmaps" ]
    verbs: [ "get", "list", "watch", "update", "create", "patch" ]
